import openai

# Put your API key here
openai.api_key = "YOUR_API_KEY_HERE"

print("Simple AI Chatbot (type 'exit' to quit)")

while True:
    user_input = input("You: ")
    if user_input.lower() == "exit":
        break

    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",  # or "gpt-4" if you have access
        messages=[{"role": "user", "content": user_input}]
    )

    ai_reply = response['choices'][0]['message']['content']
    print("AI:", ai_reply)

"""
Insert your API Key, generated by OpenAI
Do not share publicly
"""
